// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
public class selWoltTestTest {
    WebDriver driver = new ChromeDriver();
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
       // driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void selWoltTest() throws InterruptedException {
        driver.get("https://wolt.com/en/ltu");
        driver.manage().window().setSize(new Dimension(1328, 866));
        assertThat(driver.getTitle(), is("Wolt Delivery: Food and more \u2013 Lithuania"));
        driver.findElement(By.xpath("//html/body/div[5]/div/div/div/button[2]")).click();
        driver.findElement(By.id("front-page-input")).click();
        driver.findElement(By.id("front-page-input")).sendKeys("Riga");
        Thread.sleep(1000);
        driver.findElement(By.id("ChIJ7T0H5bDP7kYRMP7yaM3PAAQ")).click();
        Thread.sleep(1000);
        assertThat(driver.findElement(By.xpath("/html/body/div[2]/div[2]/main/div[1]/div/div[1]/header/div[2]/div[1]/div/div/div/div/button/div[2]/span[2]")).getText(), is("Riga"));
       driver.close();
    }
}
